apiVersion: v1
kind: Pod
metadata:
  name: myapp-be-pod
  labels:
    app: myapp
    type: back-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
      - containerPort: 80
